# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce862a4d75b3aa8faa15a39e5cafb5d3d9066ec37dfad5d83e15cedb7e77a34166ea3159425113b7ede28b4e38b775dec69019a3ddf9c1a15141a4a5ac472559

test:
  secret_key_base: e7e0f7edd9e2683b5f595834713b11c3ffb2acdc57549a9c4852a2193c0693b8f823c14aa441420db7dfb279ca7d4dbab3632a3cb7559be6c226f911c8c65f47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
